### ISSUE TITLE
無駄な処理を修正してください

### ISSUE THREAD

**Issue by shun126** [B2T11/Project_STG#2]
- vector2_t& pを外から受け取る必要がありません。
- const float& speedなどレジスタで受け取れる方は参照で渡すと速度が不利になります。
  - int, floatなどReadOnlyで標準型を参照で渡すのは意味がほとんどありません。
- インデントを整えてください。

https://github.com/B2T11/Project_STG/blob/9d397027b34a54d9fcfc08b2d3ceb461fccf8eea/BezierCurves.cpp#L4

**Comment by shun126** [comment]
> const float& speedなどレジスタで受け取れる方は参照で渡すと速度が不利になります。
> int, floatなどReadOnlyで標準型を参照で渡すのは意味がほとんどありません。

これは全てのソースファイルで誤解しています。構造体はメモリ上で操作されます。
char, short, int ,long (unsigned含む), float, doubleなど標準型はレジスタで操作されます。
レジスタが分からない場合は勉強してください。

必ずすべてコピーに修正してください。

**Comment by B2T11** [comment]
ここのspeedはコピーに修正できるけどtとかBulletShootControl.cppにあるbulletDelayTimerとかコピーになったら動かなくなる。それはどうすればいいですか。

**Comment by shun126** [comment]
理解度を試したいです。
なぜ`bulletDelayTimer`をコピーにしたらコンパイルエラーが発生したと思いますか？

**Comment by B2T11** [comment]
関数の中0を代入するからと思う。コピーしたら引数の変数の値が変わりません。

**Comment by shun126** [comment]
> 関数の中0を代入するからと思う。コピーしたら引数の変数の値が変わりません。
はい。その通りです。

まとめると…
* CPUのレジスタで計算できる型はコピーをする
* CPUのレジスタで計算できない型（structやclass等）は参照で渡す

参照で渡す時は特に**不変である事の宣言**が重要です。
参照で渡すという事は関数内で好きに書き換える事ができる事を認めています。なので書き換えない参照渡しは必ず`const`をつけるようにしてください。
そして、不変である場合はメンバー変数も徹底して宣言してください。メンバー関数が`const`という事はメンバー変数が不変（つまりthisが不変）である事を宣言しています。

```c++
class Class
{
    void hoge();
    void foo(int32_t& i) const;  // <- i は書き換える
    void fooo(const int32_t& i) const;  // <- i は書き換えない
    uint32_t mValue = 0;
};
void Class::hoge()
{
    int32_t i = 0;
    foo(i);
    if (i == 1) {}
    ++mValue; // const関数では無いのでOK
}
void Class::foo(int32_t& i) const
{
    ++i; // <- 外の情報を勝手に書き換えているが、const int32_t& iでは無いので、宣言通りと変更されるという事が分かる。
}
void Class::fooo(const int32_t& i) const
{
    ++i; // ERROR
    ++mValue; // const関数なのでERROR
}
```

**Comment by B2T11** [comment]
わかりました。じゃ私が修正したのは大丈夫ですか。

**Comment by shun126** [comment]
はい大丈夫です
